### ISSUE TITLE
Favicon, Refresh button, mouse indicator flashes when initilized

### ISSUE THREAD

**Issue by ericleethrinacia** [froala/angular-froala#54] opened 2015-12-01 01:38 UTC
I have installed the latest angular-froala and latest froala editor on our site that runs Angularjs 1.3.15

I've noticed that every time a user visits a page that contains angular-froala, the favicon, refresh button, and mouse indicator flashes between state of ready and loading very fast for short time
It become very obvious if there are more instances of editors in one page

Do you have any suggestions for this?
Thank you

**Comment by cgallarno** [comment] 2015-12-01 14:42
Hey @ericleethrinacia I belive this is the same issue as https://github.com/froala/wysiwyg-editor/issues/817, which appears to be a chrome bug with iframes. However this only happens when the entities plugin is included. Do not include the entities froala plugin and see if the problem still persists.

**Comment by stefanneculai** [comment] 2015-12-01 14:44
@cgallarno no, it's not the same. It is caused by https://github.com/froala/angular-froala/blob/master/src/angular-froala.js#L46. I believe we should add an option to `html.set` method to prevent cleaning the html for such cases. We're working on this issue.

**Comment by beyondcreed** [comment] 2015-12-01 16:28
@stefanneculai great to hear you are working on this, this has now became critical for us to resolve as froala editor is already in the production and we cannot have customers seeing this. so the sooner you can resolve it the better. thank you.

**Comment by stefanneculai** [comment] 2015-12-01 17:33
@cgallarno you are right, the issue is indeed the entities plugin. We're working to see maybe we can find a workaround.

**Comment by ericleethrinacia** [comment] 2015-12-01 18:45
@stefanneculai I commented out entities.min.js but it still does flashing on Chrome 46, FireFox 42 on Ubuntu 13.10. It sometimes happens in Mac but it's really obvious on Windows

**Comment by stefanneculai** [comment] 2015-12-02 14:02
@ericleethrinacia The problem should be fixed on the master repo `froala/wysiwyg-editor`.

**Closed** 2015-12-02 14:02 UTC
