### ISSUE TITLE
Error: Method undo.reset does not exist in Froala Editor

### ISSUE THREAD

**Issue by yanivlllev** [froala/angular-froala#92] opened 2016-03-15 10:49 UTC
hey,  i'm trying to figure out how to solve this error.... whats does it mean?
it occurs everytime a froala is initialized.

i'm using:
```
"angular": "version": "1.4.9"
"FroalaWysiwygEditor": "version": "2.0.0-rc.1"
"angular-froala": "version": "2.2.1"
```

![screen](https://cloud.githubusercontent.com/assets/12447235/13775241/1c400174-eaac-11e5-8fa3-7e9a65a13cd6.jpg)

and also another question... i have this "+" square appearing (with a tooltip that say "insert") when i hover the froala at its Lower-Right corner.... -
i have no idea where is it coming from, I can see in the devtool that it has something with the 
 a `<div class="fr-insert-helper">` and `<a "fr-floating-btn">`
![screen](https://cloud.githubusercontent.com/assets/12447235/13775828/703d251a-eaaf-11e5-86ce-0632c5acbeb5.jpg) 
What is it?

**Comment by Whyves** [comment] 2016-03-15 17:10
Hi,

For the undo.reset error, did you by any chance use the "Init On Click" Froala option. If so, the error stems from this. I had the same issue at some point but solved this by using the manual initialization controls. The Angular framework needs to track the initialize event before doing the undo.reset. Should be added as a bug I guess.

**Comment by yanivlllev** [comment] 2016-03-15 17:41
yes, i use "init on click" because i have many froalas on the same page. do you have an example for your code?

**Comment by Whyves** [comment] 2016-03-15 17:45
To manually initialize the editors, take a look at the sample 3 example in the [demo page](https://github.com/froala/angular-froala/tree/master/demo).

**Comment by stefanneculai** [comment] 2016-03-18 11:55
@yanivlllev you should upgrade your editor version to the latest one V2.2.1. You're currently using an outdated one: V2.0.0-rc.1.

**Comment by yanivlllev** [comment] 2016-03-21 08:40
@stefanneculai - i updated the versions to:
"angular": "version": "1.4.9"
"froala-wysiwyg-editor": "version": "2.2.1"
"angular-froala": "version": "2.2.1"

but i'm still getting both of those issues.. 
1. the "Method undo.reset does not exist in Froala Editor" error
2. and the `+` square when hovering the lower-right corner of the froala.

**Comment by MichaelTSS** [comment] 2016-04-25 09:18
@stefanneculai I have the same issue, and just like @yanivlllev I have many editors on the same page. I don't want to have the user click on an button to init the editor.

**Comment by henningborchers** [comment] 2016-05-13 12:13
@stefanneculai 
i also have this issue with

"angular": "1.5.5"
"angular-froala": "2.2.4"
 "froala-wysiwyg-editor": "2.2.4"

**Comment by stefanneculai** [comment] 2016-05-13 12:14
@cgallarno any thoughs on this?

**Comment by cgallarno** [comment] 2016-05-13 13:26
@stefanneculai I can't recreate the issue in my local copy, can anyone provide a jsFiddle that replicates this?

**Comment by Whyves** [comment] 2016-05-13 14:16
@stefanneculai , @cgallarno 

Let me take a look, I am pretty sure to know what the problem is as I have faced it in the past.

**Comment by MichaelTSS** [comment] 2016-05-23 17:56
@Whyves did your commit fix it? It is 10 days old and v2.3.0 was released 3 days ago without it.

**Comment by cgallarno** [comment] 2016-05-23 18:32
@Whyves Your pull request has been merged into master. cc: @MichaelTSS

**Closed by cgallarno** 2016-05-23 18:32 UTC

**Comment by MichaelTSS** [comment] 2016-05-24 07:31
@cgallarno When using the master branch, the issue seems fixed.
Thank you @Whyves for your commit!
Any plans on releasing it soon? Maybe v2.3.1?
